version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=school
      - POSTGRES_USER=shahad
      - POSTGRES_PASSWORD="1234"
  web:
    image: .
    command : pthon manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=school
      - POSTGRES_USER=shahad
      - POSTGRES_PASSWORD="1234"
    depends_on:
      - db

