# Generated by Django 4.0.4 on 2022-05-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfirst_name', models.CharField(max_length=50)),
                ('slast_name', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=254)),
                ('susername', models.CharField(max_length=30, unique=True)),
                ('spassword', models.CharField(max_length=50)),
            ],
        ),
    ]
