# Generated by Django 4.0.4 on 2022-05-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_students_spassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='semail',
            field=models.EmailField(max_length=30),
        ),
    ]
