# Generated by Django 4.0.4 on 2022-05-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='spassword',
            field=models.CharField(max_length=150),
        ),
    ]
