# Generated by Django 4.0.4 on 2022-05-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_students_semail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
    ]
