# Generated by Django 4.0.4 on 2022-05-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_students_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='semail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='sfirst_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='slast_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='spassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='susername',
            new_name='username',
        ),
    ]
