# Generated by Django 4.0.4 on 2022-05-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_semail_students_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='email',
            new_name='semail',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='first_name',
            new_name='sfirst_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='last_name',
            new_name='slast_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='password',
            new_name='spassword',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='username',
            new_name='susername',
        ),
    ]
